import { GameMode, SlippiGame } from "../src";

describe("when processing replays", () => {
  it("should properly detect the gametype", () => {
    let game;
    game = new SlippiGame("slp/gameModeTest/Versus.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.VS);
    game = new SlippiGame("slp/gameModeTest/Classic.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.CLASSIC);
    game = new SlippiGame("slp/gameModeTest/Adventure.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.ADVENTURE);
    game = new SlippiGame("slp/gameModeTest/All-Star.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.ALL_STAR);
    game = new SlippiGame("slp/gameModeTest/Online.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.ONLINE);
    game = new SlippiGame("slp/gameModeTest/Camera.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.CAMERA);
    game = new SlippiGame("slp/gameModeTest/Targets.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.TARGET_TEST);
    game = new SlippiGame("slp/gameModeTest/Super-Sudden-Death.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.SUPER_SUDDEN_DEATH);
    game = new SlippiGame("slp/gameModeTest/Invisible.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.INVISIBLE_MELEE);
    game = new SlippiGame("slp/gameModeTest/Slo-Mo.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.SLO_MO_MELEE);
    game = new SlippiGame("slp/gameModeTest/Lightning.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.LIGHTNING_MELEE);
    game = new SlippiGame("slp/gameModeTest/Training.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.TRAINING);
    game = new SlippiGame("slp/gameModeTest/Tiny.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.TINY_MELEE);
    game = new SlippiGame("slp/gameModeTest/Giant.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.GIANT_MELEE);
    game = new SlippiGame("slp/gameModeTest/Stamina.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.STAMINA_MODE);
    game = new SlippiGame("slp/gameModeTest/Home-Run-Contest.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.HOME_RUN_CONTEST);
    game = new SlippiGame("slp/gameModeTest/10-Man.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.TEN_MAN_MELEE);
    game = new SlippiGame("slp/gameModeTest/100-Man.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.HUNDRED_MAN_MELEE);
    game = new SlippiGame("slp/gameModeTest/3-Minute.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.THREE_MINUTE_MELEE);
    game = new SlippiGame("slp/gameModeTest/15-Minute.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.FIFTEEN_MINUTE_MELEE);
    game = new SlippiGame("slp/gameModeTest/Endless.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.ENDLESS_MELEE);
    game = new SlippiGame("slp/gameModeTest/Cruel.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.CRUEL_MELEE);
    game = new SlippiGame("slp/gameModeTest/Fixed-Camera.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.FIXED_CAMERA);
    game = new SlippiGame("slp/gameModeTest/Single-Button.slp");
    expect(game.getSettings()?.gameMode).toBe(GameMode.SINGLE_BUTTON);
  });
});
